// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Core.Entities;

public partial class Grade
{
    public int Id { get; set; }

    public int? TeacherId { get; set; }

    public int? StudentId { get; set; }

    public int? SubjectId { get; set; }

    public string ExamType { get; set; }

    public decimal? Score { get; set; }

    public decimal? MaxScore { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual User Student { get; set; }

    public virtual Subject Subject { get; set; }

    public virtual User Teacher { get; set; }
}