// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Core.Entities;

public partial class ParentStudent
{
    public int ParentId { get; set; }

    public int? StudentId { get; set; }

    public virtual User Parent { get; set; }

    public virtual User Student { get; set; }
}