// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Core.Entities;

public partial class Schedule
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string ImagePath { get; set; }

    public int? UserTypeId { get; set; }

    public virtual UserType UserType { get; set; }
}