// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Core.Entities;

public partial class Subject
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int? TeacherId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<Grade> Grades { get; set; } = new List<Grade>();

    public virtual User Teacher { get; set; }

    public virtual ICollection<Warning> Warnings { get; set; } = new List<Warning>();
}