// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Core.Entities;

public partial class User
{
    public int Id { get; set; }

    public int UserType { get; set; }

    public int UserId { get; set; }

    public string Password { get; set; }

    public string Email { get; set; }

    public decimal Otp { get; set; }

    public DateTime OtptimeOut { get; set; }

    public virtual UserType UserTypeNavigation { get; set; }
}