// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Core.Entities;

public partial class User
{
    public int Id { get; set; }

    public string UserId { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public int? UserTypeId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<Grade> GradeStudents { get; set; } = new List<Grade>();

    public virtual ICollection<Grade> GradeTeachers { get; set; } = new List<Grade>();

    public virtual ICollection<Otp> Otps { get; set; } = new List<Otp>();

    public virtual ParentStudent ParentStudentParent { get; set; }

    public virtual ParentStudent ParentStudentStudent { get; set; }

    public virtual ICollection<Subject> Subjects { get; set; } = new List<Subject>();

    public virtual UserType UserType { get; set; }

    public virtual ICollection<Warning> Warnings { get; set; } = new List<Warning>();
}