// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Core.Entities;

public partial class Warning
{
    public int Id { get; set; }

    public int? SubjectId { get; set; }

    public int? StudentId { get; set; }

    public string Reason { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual User Student { get; set; }

    public virtual Subject Subject { get; set; }
}